export const FETCH_USERLOGIN_REQUEST = 'FETCH_USERLOGIN_REQUEST';
export const FETCH_USERLOGIN_SUCCESS = 'FETCH_USERLOGIN_SUCCESS';
export const FETCH_USERLOGIN_FAILURE = 'FETCH_USERLOGIN_FAILURE';
export const SET_LOGOUT_USER = 'SET_LOGOUT_USER';